### ISSUE TITLE
TVOS error 400

### ISSUE THREAD

**Issue by drlucas** [hagmas/APNsKit#2]
I am trying to run APNsKit on TVOS and it appears to work as I get this message:
Succeeded sending push notification to user's registered device!

However when I add some debug to the send method 

                    print ("data: \(data)")
                      print ("data response: \(response)")

 I get an error 400.                    
data: Optional(25 bytes)
data response: Optional(HTTP/1.1 400 bad request
apns-id: 4A15144A-C2E1-4190-8BCD-7C51F572C4C1)

I have been able to get pusher from my Mac to send to this test device of mine, but it uses the legacy connection method. Any thoughts on the error and how I might be able to troubleshoot?

**Comment by hagmas** [comment]
Hi @drlucas 

Thank you for reaching out.
Just to reproduce the issue, I ran APNsKit on Xcode 8.3.3, tvOS Simulator with tvOS 10.2 and it successfully send the push notification.
At a glance, it looks weird that your response data says "HTTP/1.1 400 bad request" wheres the http request should be HTTP/2 for APNs. Would you tell me a bit more about your environment such as if you are using the actual Apple TV/ Simulator, the version of the tvOS etc...?

**Comment by drlucas** [comment]
I’ll provide more details later today - including actual code sample...using the TVOS simulator and TVOS 11 beta. Xcode v9 - beta 6

**Comment by drlucas** [comment]
Here is the code being called and the output below... 

`  func sendAlert() {
        let payload = APNsPayload(title: "WatchDog Alert", body: "Your dog hasn't reported in for a while.", badge:0)
        let request = APNsRequest(port: .p443,
                                  server: .development,
                                  deviceToken: self.iphoneID,
                                  payload: payload)
      //  print ("Payload: \(payload)")
        print ("Request: \(request)")
 
        // Create a connection that wraps up URLSession and its authentication challenges.
   
        if let connection = try? Connection(p12FileName: "aussie.ca.watchdog", passPhrase: "password") {
            // Send the request to the APNs server. The connection has to be retained until the server responses.
            connection.send(request: request, resultHandler: { result in
                switch result {
                case .success:
                    print("Succeeded sending push notification to user's registered device!")
                    print("Result was: \(result)")
                case .failure(let code, let message):
                    print("Failed to send: \(code), \(message)")
                }
            })
        }

        
    }`
Console output appears to show an HTTPS request. 
Request: APNsRequest(port: APNsKit.APNsPort.p443, server: APNsKit.APNsServer.development, deviceToken: "4871B4CBFAA9441A5A3A77423CF12CBFB6E894A0560C5ED4630D4396E9020E4B", payload: APNsKit.APNsPayload(aps: APNsKit.APNsPayload.APS(alert: APNsKit.APNsPayload.APS.Alert(title: Optional("WatchDog Alert"), body: "Your dog hasn\'t reported in for a while.", titleLocKey: nil, titleLocArgs: nil, actionLocKey: nil, locKey: nil, locArgs: nil, launchImage: nil), badge: Optional(0), sound: nil, contentAvailable: nil, mutableContent: nil, category: nil, threadId: nil), custom: nil))
https://api.development.push.apple.com:443/3/device/

Succeeded sending push notification to user's registered device!
Result was: success


If I change my passPhrase to something incorrect then I never get anything back on the console after the request line.

**Comment by hagmas** [comment]
I really appreciate for your feedback. I realized that the body of the `response: URLResponse` of the connection need to be checked to make sure the request was send successfully, not by `error == nil`.  I will fix this issue so that the detail of the error can be explored. Please give me a few days and I will update you later.

Cheers,

**Comment by hagmas** [comment]
Hi @drlucas 

I updated APNsKit to handle the error correctly and now you can see the reason of the 400 error status. I am still not sure what's the root cause of it so please let me know if there is anything I can help with it after you find it out.

Thanks

**Comment by drlucas** [comment]
Here is the error I'm getting: Failed to send: 400, MissingTopic

I'll have to do some research to see what it really means.

**Comment by hagmas** [comment]
I see. Probably your certificate supports multiple topics (typically topic is an app's bundle ID). In that case a specific topic needs to be specified in the header. Currently APNsKit doesn't have API to specify it so I will update the API. I will let you know when I update it.

**Comment by drlucas** [comment]
Most excellent - thank you for all the support!!

**Comment by hagmas** [comment]
Hi @drlucas 
I updated APNsRequest and and header fields of the request can be optionally configured like below:
```swift
// Setting header fields is optional. Refer (#1) for configurable header fields of APNs request.
let header = APNsRequest.Header(topic: "<#The topic of the remote notification#>")

// Create a APNs payload. See Apple's Payload Key Reference (#2) for its specifications.
let payload = APNsPayload(title: "Hello World!", body: "This is APNsKit.", contentAvailable: 1)
let request = APNsRequest(port: .p2197,
                          server: .development,
                          deviceToken: "<#The target device token#>",
                          header: header,    // optional
                          payload: payload)
```
I am not an expert about the certificate but I assume you need to specify the bundle id of your app as the topic. See the detail about what is topic on [this](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW5).

**Comment by drlucas** [comment]
I am getting a compile time error.... any thoughts? 

'APNsRequest.Header' initializer is inaccessible due to 'internal' protection level

func sendAlert() {
        let payload = APNsPayload(title: "WatchDog Alert", body: "Your dog hasn't reported in for a while.", badge:0)
        let request = APNsRequest(port: .p443,
                                  server: .development,
                                  deviceToken: self.iphoneID,
                                  payload: payload)
      //  print ("Payload: \(payload)")
        print ("Request: \(request)")
 
        // Setting header fields is optional. Refer (#1) for configurable header fields of APNs request.due
        let header = APNsRequest.Header(topic: "aussie.ca.watchdog")

        // Create a connection that wraps up URLSession and its authentication challenges.
   
        if let connection = try? Connection(p12FileName: "aussie.ca.watchdog", passPhrase: "Nik0bird") {
            // Send the request to the APNs server. The connection has to be retained until the server responses.
            connection.send(request: request, resultHandler: { result in
                switch result {
                case .success:
                    print("Succeeded sending push notification to user's registered device!")
                    print("Result was: \(result)")
                case .failure(let code, let message):
                    print("Failed to send: \(code), \(message)")
                }
            })
        }

        
    }

**Comment by hagmas** [comment]
Oops, sorry my bad... I fixed the issue.

**Comment by drlucas** [comment]
I no longer get a compile issue...but get an error 400 saying missing topic even though I added this line.. 
   let header = APNsRequest.Header(priority: .p10, topic: "aussie.ca.watchdog") 

Failed to send: 400, MissingTopic

I'll look around to see if I can figure out what an example topic might look like.

**Comment by drlucas** [comment]
resolved.... 

header: header, 

was missing in my request. 

I have now pushed an alert from my appletv to my iPhone. thanks for the help and the quick fix!!
